### ISSUE TITLE
Need advice for getting Datahub to connect to Kafka Schema Registry using SSL

### ISSUE THREAD

**Issue by themightylaz** [linkedin/datahub#1861]
Hi, 

Need some advice, getting crazy here.

I am already having the following env variable set in pods (cut from kubectl describe pod...):

>     Environment:
      KAFKA_BOOTSTRAP_SERVER:                                           kafka.confluent.svc.cluster.local:9092
      KAFKA_SCHEMAREGISTRY_URL:                                         https://schemaregistry.confluent.svc.cluster.local:8443
      GMS_HOST:                                                         kindred-datahub-datahub-gms
      GMS_PORT:                                                         8080
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_SSL_KEYSTORE_LOCATION:    /mnt/kindred-datahub/certs/kindred-datahub.d2-pt.aws.kindredgroup.com.keystore.jks
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_SSL_TRUSTSTORE_LOCATION:  /mnt/kindred-datahub/certs/kindred-datahub.d2-pt.aws.kindredgroup.com.truststore.jks
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_URL:                      https://schemaregistry.confluent.svc.cluster.local:8443
      SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL:                        SSL
      SPRING_KAFKA_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM:    https
      SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_LOCATION:                    /mnt/kindred-datahub/certs/kindred-datahub.d2-pt.aws.kindredgroup.com.keystore.jks
      SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_TYPE:                        JKS
      SPRING_KAFKA_PROPERTIES_SSL_PROTOCOL:                             TLS
      SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_LOCATION:                  /mnt/kindred-datahub/certs/kindred-datahub.d2-pt.aws.kindredgroup.com.truststore.jks
      SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_TYPE:                      JKS
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_SSL_KEY_PASSWORD:         <set to the key 'kindred-datahub.d2-pt.aws.kindredgroup.com.KeyPass' in secret 'kindred-datahub-certs'>         Optional: false
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_SSL_KEYSTORE_PASSWORD:    <set to the key 'kindred-datahub.d2-pt.aws.kindredgroup.com.KeyStorePass' in secret 'kindred-datahub-certs'>    Optional: false
      SPRING_KAFKA_PROPERTIES_SCHEMA_REGISTRY_SSL_TRUSTSTORE_PASSWORD:  <set to the key 'kindred-datahub.d2-pt.aws.kindredgroup.com.TrustStorePass' in secret 'kindred-datahub-certs'>  Optional: false
      SPRING_KAFKA_PROPERTIES_SSL_KEY_PASSWORD:                         <set to the key 'kindred-datahub.d2-pt.aws.kindredgroup.com.KeyPass' in secret 'kindred-datahub-certs'>         Optional: false
      SPRING_KAFKA_PROPERTIES_SSL_KEYSTORE_PASSWORD:                    <set to the key 'kindred-datahub.d2-pt.aws.kindredgroup.com.KeyStorePass' in secret 'kindred-datahub-certs'>    Optional: false
      SPRING_KAFKA_PROPERTIES_SSL_TRUSTSTORE_PASSWORD:                  <set to the key 'kindred-datahub.d2-pt.aws.kindredgroup.com.TrustStorePass' in secret 'kindred-datahub-certs'>  Optional: false
    Mounts:
      /mnt/kindred-datahub/certs from kindred-datahub-certs-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kindred-datahub-datahub-mce-consumer-token-ml4ph (ro)

But I am still hitting the following exceptions:
`kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer org.apache.kafka.common.errors.SerializationException: Error deserializing key/value for partition MetadataChangeEvent_v4-0 at offset 22. If needed, please seek past the record to continue consumption.
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id 395
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1946)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:316)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:310)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1639)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:223)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1037)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.Handshaker.process_record(Handshaker.java:965)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1064)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1367)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1395)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1379)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:185)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:347)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.schemaregistry.client.rest.RestService.sendHttpRequest(RestService.java:208)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.schemaregistry.client.rest.RestService.httpRequest(RestService.java:252)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:482)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.schemaregistry.client.rest.RestService.getId(RestService.java:475)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getSchemaByIdFromRegistry(CachedSchemaRegistryClient.java:153)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getBySubjectAndId(CachedSchemaRegistryClient.java:232)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.schemaregistry.client.CachedSchemaRegistryClient.getById(CachedSchemaRegistryClient.java:211)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:116)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.serializers.AbstractKafkaAvroDeserializer.deserialize(AbstractKafkaAvroDeserializer.java:88)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at io.confluent.kafka.serializers.KafkaAvroDeserializer.deserialize(KafkaAvroDeserializer.java:55)
kindred-datahub-datahub-mce-consumer-76b967cfbc-xcqrc datahub-mce-consumer 	at org.apache.kafka.common.serialization.Deserializer.deserialize(Deserializer.java:58)
`
What am I missing here?
Thank in advance!

**Comment by mars-lan** [comment]
Is this a self-signed certificate? If so you'll need to configure the broker to trust the CA. See https://docs.confluent.io/2.0.0/kafka/ssl.html & https://medium.com/jinternals/kafka-ssl-setup-with-self-signed-certificate-part-1-c2679a57e16c for more details.

**Comment by aivarssilins** [comment]
Hi. I work with Lars. Yes, self-signed certificate and broker trust it, so do other confluent components in the ecosystem. Error to me seems like occur when connecting to Schema Registry, SR client (JVM) does not trust CA.

**Comment by mars-lan** [comment]
Yeah that makes sense. Is this the confluent schema registry? I assume you've read through https://docs.confluent.io/current/schema-registry/security/index.html? Do you suspect that the SSL config isn't passed to the SR client correctly?

**Comment by aivarssilins** [comment]
Could be the case, have not seen detailed debug logs. We used older version of the client in our springboot components, like 5.3.1 (we have 5.3.1 platform, however in the process to upgrade to 5.5.1), and documentation just mentions to create JAVA_OPTS, SCHEMA_REGISTRY_OPTS and KAFKA_OPTS. We instead just added javax.net.ssl.<key|truststore>.<location|password> as system parameters during bootstrap. 

I guess depends which version of the client is used here, does it support passing it through schema.registry.ssl.... and how can it be validated. Is there a way to enable debug logs? @themightylaz , anything you seen in the logs regarding schema.registry.ssl being applied?

**Comment by themightylaz** [comment]
Nope, schema.registry.ssl.* isn't applied:
- 'schema.registry.ssl.keystore.password' was supplied but isn't a known config.
- 'schema.registry.ssl.truststore.location' was supplied but isn't a known config.
- 'schema.registry.ssl.keystore.location' was supplied but isn't a known config.
- 'schema.registry.ssl.key.password' was supplied but isn't a known config.
- 'schema.registry.ssl.truststore.password' was supplied but isn't a known config.

> kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 15:46:17.734 [main] INFO  o.a.k.c.consumer.ConsumerConfig - ConsumerConfig values:
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	auto.commit.interval.ms = 10000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	auto.offset.reset = latest
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	bootstrap.servers = [kafka.confluent.svc.cluster.local:9092]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	check.crcs = true
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	client.dns.lookup = default
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	client.id =
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	connections.max.idle.ms = 540000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	default.api.timeout.ms = 60000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	enable.auto.commit = true
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	exclude.internal.topics = true
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	fetch.max.bytes = 52428800
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	fetch.max.wait.ms = 500
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	fetch.min.bytes = 1
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	group.id = mce-consumer-job-client
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	heartbeat.interval.ms = 3000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	interceptor.classes = []
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	internal.leave.group.on.close = true
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	isolation.level = read_uncommitted
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	key.deserializer = class org.apache.kafka.common.serialization.StringDeserializer
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	max.partition.fetch.bytes = 1048576
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	max.poll.interval.ms = 300000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	max.poll.records = 500
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	metadata.max.age.ms = 300000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	metric.reporters = []
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	metrics.num.samples = 2
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	metrics.recording.level = INFO
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	metrics.sample.window.ms = 30000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	partition.assignment.strategy = [class org.apache.kafka.clients.consumer.RangeAssignor]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	receive.buffer.bytes = 65536
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	reconnect.backoff.max.ms = 1000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	reconnect.backoff.ms = 50
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	request.timeout.ms = 30000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	retry.backoff.ms = 100
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.client.callback.handler.class = null
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.jaas.config = null
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.kerberos.kinit.cmd = /usr/bin/kinit
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.kerberos.min.time.before.relogin = 60000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.kerberos.service.name = null
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.kerberos.ticket.renew.jitter = 0.05
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.kerberos.ticket.renew.window.factor = 0.8
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.login.callback.handler.class = null
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.login.class = null
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.login.refresh.buffer.seconds = 300
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.login.refresh.min.period.seconds = 60
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.login.refresh.window.factor = 0.8
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.login.refresh.window.jitter = 0.05
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	sasl.mechanism = GSSAPI
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	security.protocol = SSL
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	send.buffer.bytes = 131072
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	session.timeout.ms = 10000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.cipher.suites = null
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.enabled.protocols = [TLSv1.2, TLSv1.1, TLSv1]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.endpoint.identification.algorithm =
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.key.password = [hidden]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.keymanager.algorithm = SunX509
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.keystore.location = /mnt/kindred-datahub/certs/kindred-datahub.d2-pt.aws.kindredgroup.com.keystore.jks
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.keystore.password = [hidden]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.keystore.type = JKS
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.protocol = TLS
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.provider = null
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.secure.random.implementation = null
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.trustmanager.algorithm = PKIX
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.truststore.location = /mnt/kindred-datahub/certs/kindred-datahub.d2-pt.aws.kindredgroup.com.truststore.jks
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.truststore.password = [hidden]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	ssl.truststore.type = JKS
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	value.deserializer = class io.confluent.kafka.serializers.KafkaAvroDeserializer
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 15:46:17.735 [main] INFO  i.c.k.s.KafkaAvroDeserializerConfig - KafkaAvroDeserializerConfig values:
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	schema.registry.url = [https://schemaregistry.confluent.svc.cluster.local:8443]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	basic.auth.user.info = [hidden]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	auto.register.schemas = true
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	max.schemas.per.subject = 1000
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	basic.auth.credentials.source = URL
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	schema.registry.basic.auth.user.info = [hidden]
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	specific.avro.reader = false
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	value.subject.name.strategy = class io.confluent.kafka.serializers.subject.TopicNameStrategy
kindred-datahub-datahub-mce-consumer-5667948d7c-tkljr datahub-mce-consumer 	key.subject.name.strategy = class io.confluent.kafka.serializers.subject.TopicNameStrategy

**Comment by themightylaz** [comment]
[kindred-datahub-datahub-mce-consumer-5667948d7c-qwcnt.txt](https://github.com/linkedin/datahub/files/5189422/kindred-datahub-datahub-mce-consumer-5667948d7c-qwcnt.txt)

**Comment by jplaisted** [comment]
Maybe these params aren't supported by spring? Try setting them another way maybe?

https://docs.confluent.io/current/schema-registry/security/index.html

> On the client, configure the environment variables to set the SSL keystore and truststore in one of two ways:
>
>  ...
> (Legacy, on client) Set environment variables depending on the client (one of KAFKA_OPTS, SCHEMA_REGISTRY_OPTS, KSQL_OPTS):

```
export JAVA_OPTS: "-Djavax.net.ssl.trustStore=/etc/kafka/secrets/kafka.client.truststore.jks \
            -Djavax.net.ssl.trustStorePassword=<password> \
            -Djavax.net.ssl.keyStore=/etc/kafka/secrets/kafka.client.keystore.jks \
            -Djavax.net.ssl.keyStorePassword=<password>"
```


Note: `JAVA_OPTS` is probably the wrong thing to use here, but seems like there are other env vars to explore.

**Comment by mars-lan** [comment]
Might be related to https://datahubspace.slack.com/archives/CV2KB471C/p1599256394035400?

**Comment by themightylaz** [comment]
I think it is related to https://datahubspace.slack.com/archives/CV2KB471C/p1599256394035400, yes. Will the soon-coming PR use fresh version of kafka-avro-serializer that has support for schema registry SSL?

**Comment by grantatspothero** [comment]
Yes, this is probably the same issue, all the schema registry configuration was being ignored due to the old client library.

I will open a PR today

**Comment by mars-lan** [comment]
Please check and reopen this issue if https://github.com/linkedin/datahub/pull/1863 doesn't fix it.

**Comment by themightylaz** [comment]
Hi @mars-lan, I'd like to reopen then, because #1863 didn't fix schema registry ssl config (ignoring schema registry ssl config). As @grantatspothero pointed out in #1863 while this change fixes the issue with basic auth we may need a higher version of the schema registry client to get SSL support for the schema registry client.

https://docs.confluent.io/current/schema-registry/changelog.html#version-5-4-0

Attaching full log from one pod for clarity.
[kindred-datahub-datahub-mce-consumer-68bc6b6847-7zv2n.log](https://github.com/linkedin/datahub/files/5200586/kindred-datahub-datahub-mce-consumer-68bc6b6847-7zv2n.log)

**Comment by mars-lan** [comment]
@themightylaz do you mind to create a PR for this as neither I or @grantatspothero have a SSL-enabled schema registry at our fingertips to test this.

**Comment by themightylaz** [comment]
Hi @mars-lan , app is now building fine with avro serde bumped up to 5.5.1. Now will test and then create PR

**Comment by mars-lan** [comment]
Note that the build is currently broken at HEAD and will be fixed by https://github.com/linkedin/datahub/pull/1872

**Comment by emailstonl** [comment]
about themightylaz question on certificate - how did you check if ssl certificate is imported in pod's jvm? sslpoke or printing cert from cacerts. May be importing certificate of https schemaregistry step is missed.

about broken build, I continued by commenting compile dependencies- 
comment  below compile dependency in datahub/metadata-ingestion-examples/common/build.gradle and datahub/metadata-ingestion-examples/kafka-etl
compile externalDependency.kafkaSerializers

**Comment by mars-lan** [comment]
https://github.com/linkedin/datahub/pull/1872 has been merged. A rebase should fix the build error.

**Comment by mars-lan** [comment]
@themightylaz any luck with that PR?

**Comment by themightylaz** [comment]
Hi @mars-lan, had to put this on-hold, since I had more urgent stuff to continue with, sorry for that. But a colleague to me, Mayank, picked it up and will try the following:

1. - COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -p datahub build
2. - push to dockerhub
3. - deploy them to our k8s cluster
4. - verifiy gms, mae and mce now connects to the schema registry with ssl

**Comment by mars-lan** [comment]
@themightylaz the testing plan SGTM. Feel free have Mayank submit the PR after the testing.

**Comment by themightylaz** [comment]
Hi, I did the following:
1. change kafkaAvroSerde to version io.confluent:kafka-streams-avro-serde:5.5.1
2. rebuilt app
3. ran COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose -p datahub build
4. pushed to dockerhub
5. deployed to our EKS cluster

When pods restarts I can still see the following in the logs:
The configuration ‘schema.registry.ssl.keystore.password’ was supplied but isn’t a known config.
The configuration ‘schema.registry.ssl.keystore.password’ was supplied but isn’t a known config.
The configuration ‘schema.registry.ssl.truststore.location’ was supplied but isn’t a known config.
The configuration ‘schema.registry.ssl.keystore.location’ was supplied but isn’t a known config.
The configuration ‘schema.registry.ssl.key.password’ was supplied but isn’t a known config.
The configuration ‘schema.registry.ssl.truststore.password’ was supplied but isn’t a known config.

So, something missing still…. think will create a ticket for Confluent for this. 
But do you have any suggestions?

**Comment by mars-lan** [comment]
Maybe the prefix should be `kafkastore` instead of `schema.registry`? https://docs.confluent.io/current/kafka/encryption.html#encryption-ssl-schema-registry

**Comment by themightylaz** [comment]
`kindred-datahub-datahub-gms-79b6587bb-t62vj datahub-gms 08:49:56.302 [main] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'kafkastore.ssl.truststore.password' was supplied but isn't a known config.
kindred-datahub-datahub-gms-79b6587bb-t62vj datahub-gms 08:49:56.302 [main] WARN  o.a.k.c.producer.ProducerConfig - The configuration 'kafkastore.ssl.truststore.password' was supplied but isn't a known config.`

Double-checking with Confluent community: https://confluentcommunity.slack.com/archives/C4AQC0FEZ/p1600762252041800

**Comment by themightylaz** [comment]
Hi @mars-lan , actually Datahub is working now. With kafkaavroserde bumped up to 5.5.1 and using kafkastore.* made it work, even when it complains that it isn't a known config (very confusing). So I'll create a PR tomorrow.

**Comment by mars-lan** [comment]
Oh wow. Printing the wrong log is worse than not logging. Glad to hear that.

**Comment by mars-lan** [comment]
@themightylaz could you also add/update corresponding docs in your PR? Thanks!

**Comment by themightylaz** [comment]
Sure, will do that.
