### ISSUE TITLE
React frontend server won't start with Node 17

### ISSUE THREAD

**Issue by dannylee8** [linkedin/datahub#3524]
**Describe the bug**
Frontend server crashes due to webpack issue in Node 17. 

**To Reproduce**
1. Install Node 17
2. Run `yarn install && yarn start`
3. See error - 
```
Starting the development server...

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/dreamer/git/datahub/datahub-web-react/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/dreamer/git/datahub/datahub-web-react/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at iterateNormalLoaders (/home/dreamer/git/datahub/datahub-web-react/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
/home/dreamer/git/datahub/datahub-web-react/node_modules/react-scripts/scripts/start.js:19
  throw err;
  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:67:19)
    at Object.createHash (node:crypto:130:10)
    at module.exports (/home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/NormalModule.js:417:16)
    at /home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/NormalModule.js:452:10
    at /home/dreamer/git/datahub/datahub-web-react/node_modules/webpack/lib/NormalModule.js:323:13
    at /home/dreamer/git/datahub/datahub-web-react/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /home/dreamer/git/datahub/datahub-web-react/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/home/dreamer/git/datahub/datahub-web-react/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /home/dreamer/git/datahub/datahub-web-react/node_modules/react-scripts/node_modules/babel-loader/lib/index.js:59:103 {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v17.0.1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
React localhost server starts normally.

**Desktop (please complete the following information):**
 - OS: Win 10
 - Browser Chrome

**Additional context**
md5 hash algo is not available on crypto due to OpenSSL update.  Reverting to Node 16 (current LTS version) is a workaround.  

Issue on webpack is here: https://github.com/webpack/webpack/issues/14532 (closed)

**Comment by maggiehays** [comment]
@dannylee8 Just want to confirm - was this resolved?

**Comment by dannylee8** [comment]
Hi @maggiehays, unfortunately still exists.  The issue is: https://github.com/webpack/webpack/issues/14532.  However, PR for a doc update was accepted, so I closed the issue.    wdyt?

**Comment by gabe-lyons** [comment]
@dannylee8 hey- looks like the issue you linked on webpack was resolved a few days ago! Can you try again and see if everything is good?

**Comment by maggiehays** [comment]
Hey @dannylee8 - looks like this was addressed & merged! https://github.com/NervJS/taro/pull/10605

Going to keep this issue closed here, but feel free to reopen if needed.

**Comment by dannylee8** [comment]
Hi @gabe-lyons @maggiehays,
unfortunately looks like its still there.  to reproduce, download `nvm use 17` then d/l a fresh datahub repo, `./gradlew build -x test` then cd into the datahub-web-react folder.  `yarn install && yarn start`  - still failing on unsupported digital envelope routines.  

There's a hack using a switch `NODE_OPTIONS=--openssl-legacy-provider yarn start`, or dropping back to Node 16.0.0 works for me.

**Comment by dannylee8** [comment]
Just an update.  Its starting to look like the fix needs to happen in CRA, from the discussion in this issue:  https://github.com/facebook/create-react-app/issues/11562

Since Node 16 is LTS, its probably not an issue for datahub users and it looks like the bug is on the way to being rectified, I think this issue can stay closed. Thanks!

**Comment by ToanP** [comment]
`Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> Task :datahub-web-react:yarnQuickBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':datahub-web-react:yarnQuickBuild'.
> Process 'command 'yarn'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.`

**Comment by ToanP** [comment]
I am trying to setup a local environment and facing an issue with "Datahub-web-react" 

Issuing the comment " `./gradlew :datahub-frontend:dist --stacktrace`" and there was a failure with` yarnQuickbuild`

---------------------------------------------------------------------------------------------------------------
```
 Node.js v18.13.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> Task :datahub-web-react:yarnQuickBuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':datahub-web-react:yarnQuickBuild'.
> Process 'command 'yarn'' finished with non-zero exit value 1

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.
```
--------------------------------------------------------------------------------------------------------------------

**Comment by aabharti-visa** [comment]
I have the below node version
v16.16.0

I am too getting the same error as mentioned by @ToanP .  Is there a fix for this?
